"""Add config_parameters table

Revision ID: c5597ce1022c
Revises: 001_add_oauth_tokens
Create Date: 2026-01-19 21:53:59.846476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5597ce1022c'
down_revision: Union[str, None] = '001_add_oauth_tokens'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.NUMERIC(precision=10, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_category', 'config_parameters', ['category'], unique=False)
    op.create_index(op.f('ix_config_parameters_name'), 'config_parameters', ['name'], unique=True)
    op.drop_index(op.f('ix_indicators_metrics_id'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_project_id'), table_name='indicators')
    op.drop_index(op.f('ix_metrics_project_id'), table_name='metrics')
    op.drop_constraint(op.f('metrics_project_id_fkey'), 'metrics', type_='foreignkey')
    op.create_foreign_key(None, 'metrics', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_scores_indicators_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_project_id'), table_name='scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scores_project_id'), 'scores', ['project_id'], unique=False)
    op.create_index(op.f('ix_scores_indicators_id'), 'scores', ['indicators_id'], unique=False)
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.create_foreign_key(op.f('metrics_project_id_fkey'), 'metrics', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_metrics_project_id'), 'metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_indicators_project_id'), 'indicators', ['project_id'], unique=False)
    op.create_index(op.f('ix_indicators_metrics_id'), 'indicators', ['metrics_id'], unique=False)
    op.drop_index(op.f('ix_config_parameters_name'), table_name='config_parameters')
    op.drop_index('idx_config_category', table_name='config_parameters')
    op.drop_table('config_parameters')
    # ### end Alembic commands ###
