# Random password for database
resource "random_password" "db_password" {
  length  = 32
  special = false  # Avoid special chars that might cause issues in connection strings
}

# Random passwords for JWT secrets
resource "random_password" "jwt_secret" {
  length  = 64
  special = false
}

resource "random_password" "session_secret" {
  length  = 64
  special = false
}

# Secret - Database Password (auto-generated)
resource "aws_secretsmanager_secret" "db_password" {
  name        = "/${var.project_name}/${var.environment}/db-password"
  description = "Database password for ${var.project_name}"

  tags = {
    AutoGenerated = "true"
  }
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id = aws_secretsmanager_secret.db_password.id
  secret_string = jsonencode({
    password = random_password.db_password.result
    username = var.project_name
    host     = aws_db_instance.main.address
    port     = 5432
    dbname   = var.project_name
  })
}

# Secret - JWT Secrets (auto-generated)
resource "aws_secretsmanager_secret" "jwt_secrets" {
  name        = "/${var.project_name}/${var.environment}/jwt-secrets"
  description = "JWT and session secrets for ${var.project_name}"

  tags = {
    AutoGenerated = "true"
  }
}

resource "aws_secretsmanager_secret_version" "jwt_secrets" {
  secret_id = aws_secretsmanager_secret.jwt_secrets.id
  secret_string = jsonencode({
    jwt_secret_key     = random_password.jwt_secret.result
    session_secret_key = random_password.session_secret.result
  })
}

# Secret - Google OAuth (manual)
resource "aws_secretsmanager_secret" "google_oauth" {
  name        = "/${var.project_name}/${var.environment}/google-oauth"
  description = "Google OAuth credentials - FILL MANUALLY"

  tags = {
    AutoGenerated = "false"
  }
}

resource "aws_secretsmanager_secret_version" "google_oauth" {
  secret_id = aws_secretsmanager_secret.google_oauth.id
  secret_string = jsonencode({
    client_id     = "REPLACE_ME"
    client_secret = "REPLACE_ME"
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# Secret - Jira OAuth (manual)
resource "aws_secretsmanager_secret" "jira_oauth" {
  name        = "/${var.project_name}/${var.environment}/jira-oauth"
  description = "Jira OAuth credentials - FILL MANUALLY"

  tags = {
    AutoGenerated = "false"
  }
}

resource "aws_secretsmanager_secret_version" "jira_oauth" {
  secret_id = aws_secretsmanager_secret.jira_oauth.id
  secret_string = jsonencode({
    client_id     = "REPLACE_ME"
    client_secret = "REPLACE_ME"
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# Secret - GitHub (manual)
resource "aws_secretsmanager_secret" "github" {
  name        = "/${var.project_name}/${var.environment}/github"
  description = "GitHub token - FILL MANUALLY"

  tags = {
    AutoGenerated = "false"
  }
}

resource "aws_secretsmanager_secret_version" "github" {
  secret_id = aws_secretsmanager_secret.github.id
  secret_string = jsonencode({
    token = "REPLACE_ME"
    org   = "REPLACE_ME"
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# Secret - Slack (manual, optional)
resource "aws_secretsmanager_secret" "slack" {
  name        = "/${var.project_name}/${var.environment}/slack"
  description = "Slack bot token - FILL MANUALLY (optional)"

  tags = {
    AutoGenerated = "false"
  }
}

resource "aws_secretsmanager_secret_version" "slack" {
  secret_id = aws_secretsmanager_secret.slack.id
  secret_string = jsonencode({
    bot_token = "REPLACE_ME"
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}
