import { useEffect, useRef, useState, type KeyboardEvent } from 'react';
import { Lock, Pin } from 'lucide-react';
import type { AccrualCellSource } from '@/modules/accrual/types/accrual';

interface AccrualCellProps {
  readonly amount: string;
  readonly eurAmount: string | null;
  readonly isOverride: boolean;
  readonly isFrozen: boolean;
  readonly canEdit: boolean;
  readonly onChange: (newAmount: string) => void;
  readonly onError?: boolean;
  readonly source?: AccrualCellSource;
}

// Hatched diagonal-stripe pattern signals "fallback" — these cells were
// generated by the team-budget redistribute, not from an Excel row. The
// stripes are CSS-only (no SVG) so they render cheaply across the grid.
const TEAM_BUDGET_STRIPES = {
  backgroundImage:
    'repeating-linear-gradient(45deg, transparent 0 4px, hsl(var(--muted-foreground) / 0.10) 4px 5px)',
} as const;

const SOURCE_LABELS: Record<AccrualCellSource, string> = {
  excel: 'From Excel',
  team_budget: 'Team-budget fallback (no Excel data)',
  manual: 'Manual override',
};

const fmt = new Intl.NumberFormat('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

function formatAmount(value: string): string {
  const num = Number.parseFloat(value);
  return Number.isNaN(num) ? value : fmt.format(num);
}

export function AccrualCell({
  amount,
  eurAmount,
  isOverride,
  isFrozen,
  canEdit,
  onChange,
  onError,
  source = 'excel',
}: AccrualCellProps): JSX.Element {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(amount);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (editing) {
      inputRef.current?.select();
    }
  }, [editing]);

  const commit = (): void => {
    setEditing(false);
    if (draft !== amount) {
      onChange(draft);
    }
  };

  const cancel = (): void => {
    setDraft(amount);
    setEditing(false);
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>): void => {
    if (e.key === 'Enter' || e.key === 'Tab') {
      e.preventDefault();
      commit();
    } else if (e.key === 'Escape') {
      cancel();
    }
  };

  const ringClass = onError ? 'ring-2 ring-inset ring-destructive' : '';

  if (editing) {
    return (
      <div className={`relative flex h-full w-full items-center justify-center ${ringClass}`}>
        <input
          ref={inputRef}
          type="text"
          className="w-full h-full border-0 bg-transparent text-right text-xs outline-none px-1"
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onBlur={commit}
          onKeyDown={handleKeyDown}
        />
      </div>
    );
  }

  const interactive = canEdit && !isFrozen;
  const titleParts: string[] = [];
  if (eurAmount) titleParts.push(`EUR ${eurAmount}`);
  titleParts.push(SOURCE_LABELS[source]);
  const inlineStyle = source === 'team_budget' ? TEAM_BUDGET_STRIPES : undefined;
  return (
    <button
      type="button"
      title={titleParts.join(' • ')}
      data-source={source}
      style={inlineStyle}
      className={`flex h-full w-full items-center justify-end gap-1 px-1 text-xs bg-transparent border-0 select-none ${interactive ? 'cursor-pointer' : 'cursor-default'} ${ringClass}`}
      onClick={() => {
        if (interactive) {
          setDraft(amount);
          setEditing(true);
        }
      }}
    >
      {isOverride && <Pin data-testid="cell-override-pin" className="h-3 w-3 shrink-0" />}
      {isFrozen && <Lock data-testid="cell-frozen-lock" className="h-3 w-3 shrink-0" />}
      <span>{formatAmount(amount)}</span>
    </button>
  );
}
