"""DB-backed OAuth state management for CSRF protection."""

import secrets
from datetime import datetime, timedelta, timezone

from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.oauth import OAuthStateDB


class OAuthStateManager:
    """
    Manages OAuth state tokens in the database.

    Supports multi-worker deployments — any worker can validate
    a state token generated by any other worker.
    """

    @staticmethod
    async def generate_state(db: AsyncSession) -> str:
        """Generate a cryptographically secure state token and persist it."""
        state = secrets.token_urlsafe(32)
        expires_at = datetime.now(timezone.utc) + timedelta(minutes=10)

        db.add(OAuthStateDB(state=state, expires_at=expires_at))
        await db.flush()

        await OAuthStateManager.cleanup_expired(db)

        return state

    @staticmethod
    async def validate_state(state: str, db: AsyncSession) -> bool:
        """Validate and consume a state token (one-time use)."""
        result = await db.execute(
            select(OAuthStateDB).where(OAuthStateDB.state == state)
        )
        row = result.scalar_one_or_none()

        if row is None:
            return False

        await db.delete(row)
        await db.flush()

        if datetime.now(timezone.utc) > row.expires_at:
            return False

        return True

    @staticmethod
    async def cleanup_expired(db: AsyncSession) -> int:
        """Remove expired states. Returns count of removed rows."""
        now = datetime.now(timezone.utc)
        result = await db.execute(
            delete(OAuthStateDB).where(OAuthStateDB.expires_at < now)
        )
        return result.rowcount
